-- ============================================================
-- 0015: Uebungskatalog aus free-exercise-db
-- ============================================================
-- ERZEUGT von supabase/import/uebungen-import.mjs - nicht von Hand aendern.
-- Aenderungen gehoeren in uebungen-de.json oder in das Skript, danach neu
-- erzeugen.
--
-- Quelle
-- ------
-- https://github.com/yuhonas/free-exercise-db
-- Lizenz: Unlicense, also gemeinfrei. Keine Namensnennung noetig, keine
-- Weitergabepflicht. Wir nennen die Quelle trotzdem in jeder Zeile
-- (source_name, source_url, source_license), weil es sich gehoert und weil
-- spaeter nachvollziehbar sein soll, woher ein Eintrag stammt.
--
-- Auswahl
-- -------
-- Aus 873 Uebungen sind 59 uebernommen: die fuer Laufende
-- relevanten aus Kraft, Dehnen und Sprungkraft, beschraenkt auf Geraete, die
-- man zu Hause oder im Studio hat. Bodybuilding-Uebungen fuer Brust, Arme und
-- Ruecken sind bewusst aussen vor.
--
-- Texte
-- -----
-- name_de und description_de sind von Hand geschrieben, keine maschinelle
-- Uebersetzung. Die englischen Originale stehen als name_en und
-- description_en daneben. Eine fachliche Durchsicht durch Physiotherapie oder
-- Trainerin steht noch aus.
--
-- Bilder
-- ------
-- Liegen unter myprosole_web/public/uebungen/<external_id>/0.jpg und werden
-- von unserer eigenen Adresse ausgeliefert. Bewusst kein fremdes CDN: Sonst
-- erfuehre ein Dritter, welche Uebung sich wer ansieht - bei Gesundheitsdaten
-- keine Nebensaechlichkeit.
--
-- Wiederholbar: on conflict (slug) do nothing laesst bestehende Zeilen in
-- Ruhe, die 22 Uebungen aus 0007 bleiben unveraendert.
-- ============================================================

insert into public.exercises
  (slug, name_de, name_en, description_de, description_en,
   category, difficulty, modality, image_url,
   source_name, source_url, source_license, external_id) values
  ('90_90_hamstring', '90/90-Dehnung für die Oberschenkelrückseite', '90/90 Hamstring',
   'Rückenlage, ein Bein liegt gestreckt am Boden. Das andere winkelst du in Hüfte und Knie jeweils im rechten Winkel an und hältst den Oberschenkel mit den Händen. Streck nun das angewinkelte Bein nach oben, bis du die Rückseite ziehen spürst, halte kurz und geh zurück. Zehn bis zwanzig Mal, dann die Seite wechseln.',
   'Lie on your back, with one leg extended straight out. With the other leg, bend the hip and knee to 90 degrees. You may brace your leg with your hands if necessary. This will be your starting position. Extend your leg straight into the air, pausing briefly at the top. Return the leg to the starting position. Repeat for 10-20 repetitions, and then switch to the other leg.',
   'mobility', 'beginner', 'bodyweight',
   '/uebungen/90_90_Hamstring/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', '90_90_Hamstring'),
  ('adductor', 'Innenseite des Oberschenkels ausrollen', 'Adductor',
   'Leg dich auf den Bauch und winkle ein Bein seitlich an, sodass die Innenseite des Oberschenkels auf der Faszienrolle liegt. Verlagere so viel Gewicht darauf, wie du gut aushältst. Roll zwischen Hüfte und Knie hin und her und halte an schmerzhaften Stellen zehn bis dreißig Sekunden. Dann die Seite wechseln.',
   'Lie face down with one leg on a foam roll. Rotate the leg so that the foam roll contacts against your inner thigh. Shift as much weight onto the foam roll as can be tolerated. While trying to relax the muscles if the inner thigh, roll over the foam between your hip and knee, holding points of tension for 10-30 seconds. Repeat with the other leg.',
   'mobility', 'intermediate', 'both',
   '/uebungen/Adductor/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Adductor'),
  ('all_fours_quad_stretch', 'Oberschenkelvorderseite im Vierfüßlerstand dehnen', 'All Fours Quad Stretch',
   'Geh in den Vierfüßlerstand, heb ein Bein an und fass den Fuß oder Knöchel mit der Hand. Zieh die Ferse Richtung Gesäß und schieb gleichzeitig die Hüfte nach vorn unten – das verstärkt die Dehnung im Hüftbeuger. Zehn bis zwanzig Sekunden halten, dann die Seite wechseln.',
   'Start off on your hands and knees, then lift your leg off the floor and hold the foot with your hand. Use your hand to hold the foot or ankle, keeping the knee fully flexed, stretching the quadriceps and hip flexors. Focus on extending your hips, thrusting them towards the floor. Hold for 10-20 seconds and then switch sides.',
   'mobility', 'intermediate', 'bodyweight',
   '/uebungen/All_Fours_Quad_Stretch/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'All_Fours_Quad_Stretch'),
  ('ball_leg_curl', 'Beinbeugen auf dem Gymnastikball', 'Ball Leg Curl',
   'Rückenlage, die Fersen liegen oben auf einem Gymnastikball, die Beine sind gestreckt. Heb die Hüfte an, sodass das Gewicht auf Schulterblättern und Fersen liegt. Zieh den Ball mit gebeugten Knien zu dir heran und spann die hintere Oberschenkelmuskulatur an. Kurz halten, dann langsam wieder strecken.',
   'Begin on the floor laying on your back with your feet on top of the ball. Position the ball so that when your legs are extended your ankles are on top of the ball. This will be your starting position. Raise your hips off of the ground, keeping your weight on the shoulder blades and your feet. Flex the knees, pulling the ball as close to you as you can, contracting the hamstrings. After a brief pause, return to the starting position.',
   'strength', 'beginner', 'both',
   '/uebungen/Ball_Leg_Curl/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Ball_Leg_Curl'),
  ('band_hip_adductions', 'Bein anziehen mit Band', 'Band Hip Adductions',
   'Befestige ein Band unten an einem festen Punkt und leg die Schlaufe um den äußeren Knöchel. Stell dich seitlich dazu und halte dich bei Bedarf fest. Führ das Bein bei gestrecktem Knie gegen den Zug vor dem Standbein vorbei nach innen und lass es langsam zurück. Dann die Seite wechseln.',
   'Anchor a band around a solid post or other object. Stand with your left side to the post, and put your right foot through the band, getting it around the ankle. Stand up straight and hold onto the post if needed. This will be your starting position. Keeping the knee straight, raise your right legs out to the side as far as you can. Return to the starting position and repeat for the desired rep count. Switch sides.',
   'strength', 'beginner', 'both',
   '/uebungen/Band_Hip_Adductions/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Band_Hip_Adductions'),
  ('bench_jump', 'Sprung über die Bank', 'Bench Jump',
   'Stell dich schulterbreit vor eine niedrige Bank oder Box. Geh kurz in die Hocke, schwing die Arme nach hinten und spring explosiv darüber. Lande mit gebeugten Knien und fang den Aufprall über die Beine ab. Dann umdrehen und zurückspringen. Nur mit einer standfesten Bank und passender Höhe.',
   'Begin with a box or bench 1-2 feet in front of you. Stand with your feet shoulder width apart. This will be your starting position. Perform a short squat in preparation for the jump; swing your arms behind you. Rebound out of this position, extending through the hips, knees, and ankles to jump as high as possible. Swing your arms forward and up. Jump over the bench, landing with the knees bent, absorbing the impact through the legs. Turn around and face the opposite direction, then jump back over the bench.',
   'strength', 'intermediate', 'bodyweight',
   '/uebungen/Bench_Jump/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Bench_Jump'),
  ('bent_knee_hip_raise', 'Beckenheben mit gebeugten Knien', 'Bent-Knee Hip Raise',
   'Rückenlage, Arme neben dem Körper, Knie leicht gebeugt und die Füße wenige Zentimeter über dem Boden. Zieh die Knie zur Brust und roll dabei das Becken nach hinten ein, bis das Gesäß leicht abhebt. Oben kurz anspannen, dann langsam zurück. Die Bewegung kommt aus dem Bauch, nicht aus dem Schwung.',
   'Lay flat on the floor with your arms next to your sides. Now bend your knees at around a 75 degree angle and lift your feet off the floor by around 2 inches. Using your lower abs, bring your knees in towards you as you maintain the 75 degree angle bend in your legs. Continue this movement until you raise your hips off of the floor by rolling your pelvis backward. Breathe out as you perform this portion of the movement. Tip: At the end of the movement your knees will be over your chest. Squeeze your abs at the top of the movement for a second and then return to the starting position slowly as you breathe in. Tip: Maintain a controlled motion at all times. Repeat for the recommended amount of repetitions.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Bent-Knee_Hip_Raise/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Bent-Knee_Hip_Raise'),
  ('bodyweight_squat', 'Kniebeuge ohne Gewicht', 'Bodyweight Squat',
   'Stell dich schulterbreit hin, die Hände vor der Brust oder am Hinterkopf. Beuge Knie und Hüfte und schiebe das Gesäß nach hinten, als wolltest du dich setzen. Geh so tief, wie du es ohne Rundrücken schaffst, und komm zügig wieder hoch. Brust und Blick bleiben oben, die Knie drücken nach außen und kippen nicht nach innen.',
   'Stand with your feet shoulder width apart. You can place your hands behind your head. This will be your starting position. Begin the movement by flexing your knees and hips, sitting back with your hips. Continue down to full depth if you are able,and quickly reverse the motion until you return to the starting position. As you squat, keep your head and chest up and push your knees out.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Bodyweight_Squat/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Bodyweight_Squat'),
  ('butt_lift_bridge', 'Hüftbrücke', 'Butt Lift (Bridge)',
   'Rückenlage, beide Füße schulterbreit aufgestellt, Arme neben dem Körper. Drück über die Fersen die Hüfte nach oben, bis der Rumpf gerade ist. Oben eine Sekunde halten und das Gesäß fest anspannen, dann langsam ablegen. Der Rücken bleibt gerade, kein Hohlkreuz.',
   'Lie flat on the floor on your back with the hands by your side and your knees bent. Your feet should be placed around shoulder width. This will be your starting position. Pushing mainly with your heels, lift your hips off the floor while keeping your back straight. Breathe out as you perform this part of the motion and hold at the top for a second. Slowly go back to the starting position as you breathe in.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Butt_Lift_Bridge/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Butt_Lift_Bridge'),
  ('calf_raises_with_bands', 'Wadenheben mit Band', 'Calf Raises - With Bands',
   'Stell dich mit den Fußballen auf ein Widerstandsband und halte die Enden auf Schulterhöhe, sodass Spannung entsteht. Drück dich langsam auf die Zehenspitzen und spann die Waden oben fest an. Nach einer Sekunde kontrolliert absenken. Gute Variante für zu Hause, wenn keine Hanteln da sind.',
   'Grab an exercise band and stand on it with your toes making sure that the length of the band between the foot and the arms is the same for both sides. While holding the handles of the band, raise the arms to the side of your head as if you were getting ready to perform a shoulder press. The palms should be facing forward with the elbows bent and to the sides. This movement will create tension on the band. This will be your starting position. Keeping the hands by your shoulder, stand up on your toes as you exhale and contract the calves hard at the top of the movement. After a one second contraction, slowly go back down to the starting position. Repeat for the recommended amount of repetitions.',
   'strength', 'beginner', 'both',
   '/uebungen/Calf_Raises_-_With_Bands/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Calf_Raises_-_With_Bands'),
  ('calves_smr', 'Waden ausrollen', 'Calves-SMR',
   'Setz dich hin und leg einen Unterschenkel auf eine Faszienrolle, das andere Bein kannst du darüberlegen, um den Druck zu erhöhen. Stütz dich mit den Händen ab und heb das Gesäß an. Roll von unterhalb des Knies bis oberhalb des Knöchels und halte an schmerzhaften Stellen zehn bis dreißig Sekunden.',
   'Begin seated on the floor. Place a foam roller underneath your lower leg. Your other leg can either be crossed over the opposite or be placed on the floor, supporting some of your weight. This will be your starting position. Place your hands to your side or just behind you, and press down to raise your hips off of the floor, placing much of your weight against your calf muscle. Roll from below the knee to above the ankle, pausing at points of tension for 10-30 seconds. Repeat for the other leg.',
   'mobility', 'intermediate', 'both',
   '/uebungen/Calves-SMR/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Calves-SMR'),
  ('cross_body_crunch', 'Diagonaler Crunch', 'Cross-Body Crunch',
   'Rückenlage, Knie gebeugt, Füße aufgestellt, Hände locker am Hinterkopf. Führ Schulter und Ellbogen der einen Seite zum gegenüberliegenden Knie und zieh dieses Knie gleichzeitig entgegen. Nicht am Kopf ziehen – die Bewegung kommt aus der seitlichen Bauchmuskulatur. Im Wechsel arbeiten.',
   'Lie flat on your back and bend your knees about 60 degrees. Keep your feet flat on the floor and place your hands loosely behind your head. This will be your starting position. Now curl up and bring your right elbow and shoulder across your body while bring your left knee in toward your left shoulder at the same time. Reach with your elbow and try to touch your knee. Exhale as you perform this movement. Tip: Try to bring your shoulder up towards your knee rather than just your elbow and remember that the key is to contract the abs as you perform the movement; not just to move the elbow. Now go back down to the starting position as you inhale and repeat with the left elbow and the right knee. Continue alternating in this manner until all prescribed repetitions are done.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Cross-Body_Crunch/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Cross-Body_Crunch'),
  ('dead_bug', 'Dead Bug', 'Dead Bug',
   'Rückenlage, Arme senkrecht nach oben, Hüfte und Knie im rechten Winkel angehoben. Atme aus und drück den unteren Rücken flach auf den Boden – diese Spannung hältst du die ganze Zeit. Streck nun ein Bein langsam aus, bis die Ferse knapp über dem Boden schwebt, und führ es zurück. Sobald der Rücken sich vom Boden löst, ist die Bewegung zu groß.',
   'Begin lying on your back with your hands extended above you toward the ceiling. Bring your feet, knees, and hips up to 90 degrees. Exhale hard to bring your ribcage down and flatten your back onto the floor, rotating your pelvis up and squeezing your glutes. Hold this position throughout the movement. This will be your starting position. Initiate the exercise by extending one leg, straightening the knee and hip to bring the leg just above the ground. Maintain the position of your lumbar and pelvis as you perform the movement, as your back is going to want to arch. Stay tight and return the working leg to the starting position. Repeat on the opposite side, alternating until the set is complete.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Dead_Bug/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Dead_Bug'),
  ('double_leg_butt_kick', 'Anfersen im Sprung', 'Double Leg Butt Kick',
   'Steh mit leicht gebeugten Knien. Geh kurz in die Hocke und spring explosiv nach oben. Zieh in der Luft beide Fersen zum Gesäß. Landung mit leicht gebeugten Knien abfedern. Trainiert die schnelle Kraft, die du beim Abdruck brauchst.',
   'Begin standing with your knees slightly bent. Quickly squat a short distance, flexing the hips and knees, and immediately extend to jump for maximum vertical height. As you go up, tuck your heels by flexing the knees, attempting to touch the buttocks. Finish the motion by landing with the knees only partially bent, using your legs to absorb the impact.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Double_Leg_Butt_Kick/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Double_Leg_Butt_Kick'),
  ('dumbbell_lunges', 'Ausfallschritt mit Kurzhanteln', 'Dumbbell Lunges',
   'Steh aufrecht, in jeder Hand eine Kurzhantel. Mach einen großen Schritt nach vorn und senke den Oberkörper ab, bis das hintere Knie fast den Boden berührt. Der Oberkörper bleibt aufrecht, das vordere Schienbein senkrecht – das Knie schiebt nicht über die Fußspitze hinaus. Drück dich über die Ferse zurück und wechsle die Seite.',
   'Stand with your torso upright holding two dumbbells in your hands by your sides. This will be your starting position. Step forward with your right leg around 2 feet or so from the foot being left stationary behind and lower your upper body down, while keeping the torso upright and maintaining balance. Inhale as you go down. Note: As in the other exercises, do not allow your knee to go forward beyond your toes as you come down, as this will put undue stress on the knee joint. Make sure that you keep your front shin perpendicular to the ground. Using mainly the heel of your foot, push up and go back to the starting position as you exhale. Repeat the movement for the recommended amount of repetitions and then perform with the left leg.',
   'strength', 'beginner', 'gym',
   '/uebungen/Dumbbell_Lunges/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Dumbbell_Lunges'),
  ('dumbbell_rear_lunge', 'Ausfallschritt rückwärts mit Kurzhanteln', 'Dumbbell Rear Lunge',
   'Wie der Ausfallschritt nach vorn, nur setzt du das Bein nach hinten. Das ist für die Knie schonender, weil das vordere Knie weniger nach vorn wandert. Oberkörper aufrecht halten, über die Ferse des vorderen Fußes zurückdrücken. Ein langer Schritt fordert mehr das Gesäß, ein kurzer mehr den Oberschenkel.',
   'Stand with your torso upright holding two dumbbells in your hands by your sides. This will be your starting position. Step backward with your right leg around two feet or so from the left foot and lower your upper body down, while keeping the torso upright and maintaining balance. Inhale as you go down. Tip: As in the other exercises, do not allow your knee to go forward beyond your toes as you come down, as this will put undue stress on the knee joint. Make sure that you keep your front shin perpendicular to the ground. Keep the torso upright during the lunge; flexible hip flexors are important. A long lunge emphasizes the Gluteus Maximus; a short lunge emphasizes Quadriceps. Push up and go back to the starting position as you exhale. Tip: Use the ball of your feet to push in order to accentuate the quadriceps. To focus on the glutes, press with your heels. Now repeat with the opposite leg.',
   'strength', 'intermediate', 'gym',
   '/uebungen/Dumbbell_Rear_Lunge/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Dumbbell_Rear_Lunge'),
  ('dumbbell_seated_one_leg_calf_raise', 'Einbeiniges Wadenheben im Sitzen', 'Dumbbell Seated One-Leg Calf Raise',
   'Setz dich auf eine Bank und leg eine Kurzhantel auf den Oberschenkel, gut eine Handbreit oberhalb des Knies. Stell den Fußballen auf eine kleine Erhöhung. Drück die Ferse so weit wie möglich nach oben, kurz halten, dann tief absenken. Im Sitzen trifft es vor allem den tiefer liegenden Schollenmuskel – der arbeitet beim Laufen dauerhaft mit.',
   'Place a block on the floor about 12 inches from a flat bench. Sit on a flat bench and place a dumbbell on your upper left thigh about 3 inches above your knee. Now place the ball of your left foot on the block. This will be your starting position. Raise your toes up as high as possible as you exhale and you contract your calf muscle. Hold the contraction for a second. Slowly return to the starting position, stretching as far down as possible. Repeat for your prescribed number of repetitions and then repeat with the right leg.',
   'strength', 'beginner', 'gym',
   '/uebungen/Dumbbell_Seated_One-Leg_Calf_Raise/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Dumbbell_Seated_One-Leg_Calf_Raise'),
  ('fast_skipping', 'Schneller Hopserlauf', 'Fast Skipping',
   'Beginne locker mit einem Bein leicht vorn. Lauf im Wechsel rechts-rechts, links-links – also Schritt und Hüpfer je Seite. Halte den Bodenkontakt dabei so kurz wie möglich und bleib flach; es geht um Frequenz, nicht um Höhe. Sehr gutes Techniktraining für einen schnellen Fußaufsatz.',
   'Start in a relaxed position with one leg slightly forward. This will be your starting position. Skip by executing a step-hop pattern of right-right-step to left-left-step, and so on, alternating back and forth. Perform fast skips by maintaining close contact with the ground and reduce air time, moving as quickly as possible.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Fast_Skipping/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Fast_Skipping'),
  ('flutter_kicks', 'Beinschlag in Bauchlage', 'Flutter Kicks',
   'Leg dich mit dem Bauch auf eine Bank, sodass die Hüfte an der Kante endet und die Beine frei hängen. Halt dich vorn an der Bank fest und heb die gestreckten Beine auf Hüfthöhe. Bewege die Beine nun abwechselnd auf und ab, wie beim Kraulschwimmen. Ruhig und kontrolliert, nicht aus dem Schwung.',
   'On a flat bench lie facedown with the hips on the edge of the bench, the legs straight with toes high off the floor and with the arms on top of the bench holding on to the front edge. Squeeze your glutes and hamstrings and straighten the legs until they are level with the hips. This will be your starting position. Start the movement by lifting the left leg higher than the right leg. Then lower the left leg as you lift the right leg. Continue alternating in this manner (as though you are doing a flutter kick in water) until you have done the recommended amount of repetitions for each leg. Make sure that you keep a controlled movement at all times. Tip: You will breathe normally as you perform this movement.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Flutter_Kicks/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Flutter_Kicks'),
  ('glute_kickback', 'Beinheben im Vierfüßlerstand', 'Glute Kickback',
   'Geh in den Vierfüßlerstand, Hände unter den Schultern, Knie im rechten Winkel. Heb ein Bein nach hinten an, bis der Oberschenkel in einer Linie mit dem Rücken steht – der Winkel im Knie bleibt dabei erhalten. Oben kurz das Gesäß anspannen, dann kontrolliert absenken. Der Rücken bleibt ruhig, kein Ausweichen ins Hohlkreuz.',
   'Kneel on the floor or an exercise mat and bend at the waist with your arms extended in front of you (perpendicular to the torso) in order to get into a kneeling push-up position but with the arms spaced at shoulder width. Your head should be looking forward and the bend of the knees should create a 90-degree angle between the hamstrings and the calves. This will be your starting position. As you exhale, lift up your right leg until the hamstrings are in line with the back while maintaining the 90-degree angle bend. Contract the glutes throughout this movement and hold the contraction at the top for a second. Tip: At the end of the movement the upper leg should be parallel to the floor while the calf should be perpendicular to it. Go back to the initial position as you inhale and now repeat with the left leg. Continue to alternate legs until all of the recommended repetitions have been performed.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Glute_Kickback/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Glute_Kickback'),
  ('groiners', 'Groiner', 'Groiners',
   'Beginn in der Liegestützposition. Spring mit beiden Füßen nach vorn, sodass sie neben deinen Händen landen, und halte den Kopf oben. Spring zurück in die Ausgangsposition und wiederhole zügig. Öffnet die Hüfte und eignet sich gut zum Warmmachen vor dem Lauf.',
   'Begin in a pushup position on the floor. This will be your starting position. Using both legs, jump forward landing with your feet next to your hands. Keep your head up as you do so. Return to the starting position and immediately repeat the movement, continuing for 10-20 repetitions.',
   'mobility', 'intermediate', 'bodyweight',
   '/uebungen/Groiners/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Groiners'),
  ('hamstring_smr', 'Oberschenkelrückseite ausrollen', 'Hamstring-SMR',
   'Setz dich hin und leg die Rückseite der Oberschenkel auf eine Faszienrolle, die Hände stützen hinter dir. Heb das Gesäß an und verlagere das Gewicht auf ein Bein. Roll langsam von unterhalb des Gesäßes bis oberhalb der Kniekehle. An schmerzhaften Stellen zehn bis dreißig Sekunden verweilen und bewusst locker lassen.',
   'In a seated position, extend your legs over a foam roll so that it is position on the back of the upper legs. Place your hands to the side or behind you to help support your weight. This will be your starting position. Using your hands, lift your hips off of the floor and shift your weight on the foam roll to one leg. Relax the hamstrings of the leg you are stretching. Roll over the foam from below the hip to above the back of the knee, pausing at points of tension for 10-30 seconds. Repeat for the other leg.',
   'mobility', 'beginner', 'both',
   '/uebungen/Hamstring-SMR/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Hamstring-SMR'),
  ('hip_extension_with_bands', 'Hüftstrecken mit Band', 'Hip Extension with Bands',
   'Befestige ein Band unten an einem festen Punkt und leg die Schlaufe um einen Knöchel. Stell dich zum Befestigungspunkt hin und halte dich fest. Führ das Bein bei gestrecktem Knie so weit wie möglich nach hinten und komm langsam zurück. Brust und Kopf bleiben oben.',
   'Secure one end of the band to the lower portion of a post and attach the other to one ankle. Facing the attachment point of the band, hold on to the column to stabilize yourself. Keeping your head and your chest up, move the resisted leg back as far as you can while keeping the knee straight. Return the leg to the starting position.',
   'strength', 'beginner', 'both',
   '/uebungen/Hip_Extension_with_Bands/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Hip_Extension_with_Bands'),
  ('hip_flexion_with_band', 'Knieheben gegen Band', 'Hip Flexion with Band',
   'Befestige ein Band unten an einem festen Punkt und leg die Schlaufe um einen Knöchel. Stell dich mit dem Rücken zum Befestigungspunkt. Zieh das Knie gegen den Widerstand bis auf Hüfthöhe nach oben, kurz halten und langsam absenken. Trainiert den Hüftbeuger, der beim Laufen das Bein nach vorn bringt.',
   'Secure one end of the band to the lower portion of a post and attach the other to one ankle. Face away from the attachment point of the band. Keeping your head and your chest up, raise your knee up to 90 degrees and pause. Return the leg to the starting position.',
   'strength', 'beginner', 'both',
   '/uebungen/Hip_Flexion_with_Band/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Hip_Flexion_with_Band'),
  ('hyperextensions_with_no_hyperextension_bench', 'Rückenstrecken auf der Bank', 'Hyperextensions With No Hyperextension Bench',
   'Leg dich mit dem Bauch auf eine Bank, sodass die Hüfte an der Kante endet und der Oberkörper frei hängt. Die Beine müssen fixiert sein, notfalls von einer zweiten Person. Senke den Oberkörper mit geradem Rücken langsam ab, bis du die hintere Oberschenkelmuskulatur ziehen spürst, und richte dich wieder bis zur Streckung auf. Nicht ins Hohlkreuz überstrecken und nicht schwingen.',
   'With someone holding down your legs, slide yourself down to the edge a flat bench until your hips hang off the end of the bench. Tip: Your entire upper body should be hanging down towards the floor. Also, you will be in the same position as if you were on a hyperextension bench but the range of motion will be shorter due to the height of the flat bench vs. that of the hyperextension bench. With your body straight, cross your arms in front of you (my preference) or behind your head. This will be your starting position. Tip: You can also hold a weight plate for extra resistance in front of you under your crossed arms. Start bending forward slowly at the waist as far as you can while keeping your back flat. Inhale as you perform this movement. Keep moving forward until you almost touch the floor or you feel a nice stretch on the hamstrings (whichever comes first). Tip: Never round the back as you perform this exercise. Slowly raise your torso back to the initial position as you exhale. Tip: Avoid the temptation to arch your back past a straight line. Also, do not swing the torso at any time in order to protect the back from injury. Repeat for the recommended amount of repetitions.',
   'strength', 'intermediate', 'bodyweight',
   '/uebungen/Hyperextensions_With_No_Hyperextension_Bench/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Hyperextensions_With_No_Hyperextension_Bench'),
  ('iliotibial_tract_smr', 'Iliotibialband ausrollen', 'Iliotibial Tract-SMR',
   'Leg dich seitlich auf eine Faszienrolle, die zwischen Hüfte und Knie an der Außenseite des unteren Beins liegt. Das obere Bein kannst du davor abstellen, um das Gewicht zu dosieren. Roll langsam von der Hüfte bis kurz oberhalb des Knies. Das kann unangenehm sein – geh nicht bis in den Schmerz, und roll nicht direkt über das Knie.',
   'Lay on your side, with the bottom leg placed onto a foam roller between the hip and the knee. The other leg can be crossed in front of you. Place as much of your weight as is tolerable onto your bottom leg; there is no need to keep your bottom leg in contact with the ground. Be sure to relax the muscles of the leg you are stretching. Roll your leg over the foam from you hip to your knee, pausing for 10-30 seconds at points of tension. Repeat with the opposite leg.',
   'mobility', 'intermediate', 'both',
   '/uebungen/Iliotibial_Tract-SMR/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Iliotibial_Tract-SMR'),
  ('inchworm', 'Inchworm', 'Inchworm',
   'Stell dich hin, beuge dich mit möglichst gestreckten Beinen nach vorn und setz die Hände vor den Füßen auf. Lauf mit den Händen nach vorn, bis du in der Liegestützposition bist. Dann lass die Hände stehen und geh mit kleinen Schritten mit den Füßen wieder nach vorn. Beine dabei so gestreckt halten, wie es geht.',
   'Stand with your feet close together. Keeping your legs straight, stretch down and put your hands on the floor directly in front of you. This will be your starting position. Begin by walking your hands forward slowly, alternating your left and your right. As you do so, bend only at the hip, keeping your legs straight. Keep going until your body is parallel to the ground in a pushup position. Now, keep your hands in place and slowly take short steps with your feet, moving only a few inches at a time. Continue walking until your feet are by hour hands, keeping your legs straight as you do so.',
   'mobility', 'beginner', 'bodyweight',
   '/uebungen/Inchworm/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Inchworm'),
  ('knee_circles', 'Kniekreisen', 'Knee Circles',
   'Stell dich mit geschlossenen Beinen hin, die Hände auf den Knien, und beuge die Knie leicht. Kreise die Knie langsam in beide Richtungen und atme dabei ruhig weiter. Eine kleine Aufwärmübung, die die Gelenke auf Belastung vorbereitet – ohne Kraftaufwand.',
   'Stand with your legs together and hands by your waist. Now move your knees in a circular motion as you breathe normally. Repeat for the recommended amount of repetitions.',
   'mobility', 'beginner', 'bodyweight',
   '/uebungen/Knee_Circles/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Knee_Circles'),
  ('knee_tuck_jump', 'Sprung mit Knieanziehen', 'Knee Tuck Jump',
   'Steh mit leicht gebeugten Knien, die Handflächen auf Brusthöhe vor dem Körper. Geh kurz in die Viertelkniebeuge und spring explosiv hoch. Zieh dabei die Knie so weit an, dass sie die Handflächen berühren. Zur Landung die Beine wieder strecken und den Aufprall über die Knie abfedern.',
   'Begin in a comfortable standing position with your knees slightly bent. Hold your hands in front of you, palms down with your fingertips together at chest height. This will be your starting position. Rapidly dip down into a quarter squat and immediately explode upward. Drive the knees towards the chest, attempting to touch them to the palms of the hands. Jump as high as you can, raising your knees up, and then ensure a good land be re-extending your legs, absorbing impact through be allowing the knees to rebend.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Knee_Tuck_Jump/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Knee_Tuck_Jump'),
  ('lateral_bound', 'Seitlicher Sprung', 'Lateral Bound',
   'Geh in eine halbe Kniebeuge, quer zur Sprungrichtung. Verlagere das Gewicht auf das äußere Bein und spring so weit wie möglich zur Seite. Fang die Landung einbeinig weich ab und spring sofort in die Gegenrichtung zurück. Trainiert die seitliche Stabilität, die beim Laufen jeden Schritt sichert.',
   'Assume a half squat position facing 90 degrees from your direction of travel. This will be your starting position. Allow your lead leg to do a countermovement inward as you shift your weight to the outside leg. Immediately push off and extend, attempting to bound to the side as far as possible. Upon landing, immediately push off in the opposite direction, returning to your original start position. Continue back and forth for several repetitions.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Lateral_Bound/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Lateral_Bound'),
  ('lower_back_smr', 'Unteren Rücken ausrollen', 'Lower Back-SMR',
   'Setz dich vor eine Faszienrolle und leg dich so zurück, dass sie unter dem unteren Rücken liegt. Kreuz die Arme vor der Brust und heb die Hüfte an. Verlagere das Gewicht leicht zu einer Seite, sodass der Druck neben der Wirbelsäule liegt und nicht darauf. An verspannten Stellen zehn bis dreißig Sekunden bleiben.',
   'In a seated position, place a foam roll under your lower back. Cross your arms in front of you and protract your shoulders. This will be your starting position. Raise your hips off of the floor and lean back, keeping your weight on your lower back. Now shift your weight slightly to one side, keeping your weight off of the spine and on the muscles to the side of it. Roll over your lower back, holding points of tension for 10-30 seconds. Repeat on the other side.',
   'mobility', 'beginner', 'both',
   '/uebungen/Lower_Back-SMR/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Lower_Back-SMR'),
  ('lying_crossover', 'Überkreuz-Dehnung in Rückenlage', 'Lying Crossover',
   'Rückenlage, beide Beine gestreckt. Führ ein angewinkeltes Knie über den Körper zur gegenüberliegenden Seite Richtung Boden. Die Schulter der anderen Seite bleibt am Boden – dort entsteht die Dehnung. Zwanzig bis dreißig Sekunden ruhig halten, dann die Seite wechseln.',
   'Lie on your back with your legs extended. Cross one leg over your body with the knee bent, attempting to touch the knee to the ground. Your partner should kneel beside you, holding your shoulder down with one hand and controlling the crossed leg with the other. this will be your starting position. Attempt to raise the bent knee off of the ground as your partner prevents any actual movement. After 10-20 seconds, relax the leg as your partner gently presses the knee towards the floor. Repeat with the other side.',
   'mobility', 'advanced', 'bodyweight',
   '/uebungen/Lying_Crossover/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Lying_Crossover'),
  ('lying_glute', 'Gesäßdehnung in Rückenlage', 'Lying Glute',
   'Rückenlage, ein Knöchel liegt über dem gegenüberliegenden Knie – die Beine bilden eine Vier. Greif mit beiden Händen unter den Oberschenkel des unteren Beins und zieh es zur Brust, bis es im Gesäß der oberen Seite zieht. Kopf und Schultern bleiben am Boden. Zwanzig bis dreißig Sekunden halten, dann wechseln.',
   'Lie on your back with your partner kneeling beside you. Flex the hip of one leg, raising it off of the floor. Rotate the leg so the foot is over the opposite hip, the lower leg perpendicular to your body. Your partner should hold the knee and ankle in place. This will be your starting position. Attempt to push your leg towards your partner, who should be preventing any actual movement of the leg. After 10-20 seconds, completely relax as your partner gently pushes the ankle and knee towards your chest. Be sure to inform your helper when the stretch is adequate to prevent injury or overstretching.',
   'mobility', 'advanced', 'bodyweight',
   '/uebungen/Lying_Glute/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Lying_Glute'),
  ('lying_prone_quadriceps', 'Oberschenkelvorderseite in Bauchlage dehnen', 'Lying Prone Quadriceps',
   'Leg dich auf den Bauch, beuge ein Knie und fass den Fuß mit der gleichseitigen Hand. Zieh die Ferse sanft Richtung Gesäß, bis du die Vorderseite ziehen spürst. Das Becken bleibt am Boden, kein Hohlkreuz. Zwanzig bis dreißig Sekunden halten, dann wechseln.',
   'Lay face down on the floor with your partner kneeling beside you. Flex one knee and raise that leg off the ground, attempting to touch your glutes with your foot. Your partner should hold the knee and ankle. This will be your starting position. Attempt to extend your knee while your partner prevents any actual movement. After 10-20 seconds, relax your muscles as your partner gently pushes the foot towards your glutes, further stretching the quadriceps and hip flexors. After 10-20 seconds, switch sides.',
   'mobility', 'advanced', 'bodyweight',
   '/uebungen/Lying_Prone_Quadriceps/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Lying_Prone_Quadriceps'),
  ('monster_walk', 'Monster Walk mit Band', 'Monster Walk',
   'Leg ein Band um beide Knöchel und ein zweites um beide Knie, straff genug, dass bei schulterbreitem Stand Spannung anliegt. Geh in leichter Kniebeuge mit kurzen Schritten vorwärts, dann rückwärts zurück. Die Knie dürfen nicht nach innen fallen. Trainiert die seitliche Hüftmuskulatur, die beim Laufen das Becken stabilisiert.',
   'Place a band around both ankles and another around both knees. There should be enough tension that they are tight when your feet are shoulder width apart. To begin, take short steps forward alternating your left and right foot. After several steps, do just the opposite and walk backward to where you started.',
   'strength', 'beginner', 'both',
   '/uebungen/Monster_Walk/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Monster_Walk'),
  ('natural_glute_ham_raise', 'Beinbeuger-Absenken (Nordic Curl)', 'Natural Glute Ham Raise',
   'Knie dich hin und lass dir die Fersen fixieren, etwa unter einer Polsterstange oder von einer zweiten Person. Halte den Körper gerade von den Knien bis zum Kopf und senke dich langsam nach vorn ab, so weit du bremsen kannst. Fang mit den Händen ab und drück dich zurück. Sehr anspruchsvoll – lieber wenige saubere Wiederholungen.',
   'Using the leg pad of a lat pulldown machine or a preacher bench, position yourself so that your ankles are under the pads, knees on the seat, and you are facing away from the machine. You should be upright and maintaining good posture. This will be your starting position. Lower yourself under control until your knees are almost completely straight. Remaining in control, raise yourself back up to the starting position. If you are unable to complete a rep, use a band, a partner, or push off of a box to aid in completing a repetition.',
   'strength', 'intermediate', 'bodyweight',
   '/uebungen/Natural_Glute_Ham_Raise/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Natural_Glute_Ham_Raise'),
  ('peroneals_smr', 'Wadenaußenseite ausrollen', 'Peroneals-SMR',
   'Leg dich seitlich auf den Unterarm, die Faszienrolle liegt an der Außenseite des unteren Unterschenkels. Heb die Hüfte an und roll von unterhalb des Knies bis oberhalb des Knöchels. An schmerzhaften Stellen zehn bis dreißig Sekunden bleiben, dann die Seite wechseln.',
   'Lay on your side, supporting your weight on your forearm and on a foam roller placed on the outside of your lower leg. Your upper leg can either be on top of your lower leg, or you can cross it in front of you. This will be your starting position. Raise your hips off of the ground and begin to roll from below the knee to above the ankle on the side of your leg, pausing at points of tension for 10-30 seconds. Repeat on the other leg.',
   'mobility', 'intermediate', 'both',
   '/uebungen/Peroneals-SMR/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Peroneals-SMR'),
  ('piriformis_smr', 'Gesäßmuskulatur ausrollen', 'Piriformis-SMR',
   'Setz dich auf eine Faszienrolle und leg einen Knöchel über das gegenüberliegende Knie. Verlagere das Gewicht auf die Seite des überkreuzten Beins und roll über den Gesäßmuskel. An schmerzhaften Stellen zehn bis dreißig Sekunden bleiben. Häufig verspannt bei Laufenden und eine typische Ursache für Beschwerden, die ins Bein ausstrahlen.',
   'Sit with your buttocks on top of a foam roll. Bend your knees, and then cross one leg so that the ankle is over the knee. This will be your starting position. Shift your weight to the side of the crossed leg, rolling over the buttocks until you feel tension in your upper glute. You may assist the stretch by using one hand to pull the bent knee towards your chest. Hold this position for 10-30 seconds, and then switch sides.',
   'mobility', 'intermediate', 'both',
   '/uebungen/Piriformis-SMR/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Piriformis-SMR'),
  ('plank', 'Unterarmstütz (Plank)', 'Plank',
   'Stütz dich auf Unterarme und Fußspitzen, die Ellbogen genau unter den Schultern. Der Körper bildet eine gerade Linie von Kopf bis Ferse – kein Durchhängen im Rücken, kein Hochschieben des Gesäßes. Bauch und Gesäß aktiv anspannen und die Position halten. Steigern kannst du, indem du einen Arm oder ein Bein anhebst.',
   'Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder. Keep your body straight at all times, and hold this position as long as possible. To increase difficulty, an arm or leg can be raised.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Plank/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Plank'),
  ('quadriceps_smr', 'Oberschenkelvorderseite ausrollen', 'Quadriceps-SMR',
   'Leg dich auf den Bauch und stütz dich auf die Unterarme. Eine Faszienrolle liegt unter dem Oberschenkel, das Bein bleibt möglichst locker. Roll langsam von oberhalb des Knies bis unterhalb der Hüfte und halte an schmerzhaften Stellen zehn bis dreißig Sekunden. Dann die Seite wechseln.',
   'Lay facedown on the floor with your weight supported by your hands or forearms. Place a foam roll underneath one leg on the quadriceps, and keep the foot off of the ground. Make sure to relax the leg as much as possible. This will be your starting position. Shifting as much weight onto the leg to be stretched as is tolerable, roll over the foam from above the knee to below the hip, holding points of tension for 10-30 seconds. Switch sides.',
   'mobility', 'intermediate', 'both',
   '/uebungen/Quadriceps-SMR/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Quadriceps-SMR'),
  ('reverse_crunch', 'Umgekehrter Crunch', 'Reverse Crunch',
   'Rückenlage, Arme flach neben dem Körper, die Oberschenkel senkrecht nach oben. Roll das Becken nach hinten ein und heb die Hüfte vom Boden, bis die Knie Richtung Brust zeigen. Kurz halten und langsam ablegen. Nicht schwingen – die Bewegung ist klein und kommt aus dem unteren Bauch.',
   'Lie down on the floor with your legs fully extended and arms to the side of your torso with the palms on the floor. Your arms should be stationary for the entire exercise. Move your legs up so that your thighs are perpendicular to the floor and feet are together and parallel to the floor. This is the starting position. While inhaling, move your legs towards the torso as you roll your pelvis backwards and you raise your hips off the floor. At the end of this movement your knees will be touching your chest. Hold the contraction for a second and move your legs back to the starting position while exhaling. Repeat for the recommended amount of repetitions.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Reverse_Crunch/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Reverse_Crunch'),
  ('rocket_jump', 'Strecksprung', 'Rocket Jump',
   'Stell dich locker schulterbreit hin, die Arme am Körper. Geh halb in die Knie und spring explosiv so hoch wie möglich, dabei streckst du den ganzen Körper und die Arme nach oben. Landung weich über die Beine abfedern.',
   'Begin in a relaxed stance with your feet shoulder width apart and hold your arms close to the body. To initiate the move, squat down halfway and explode back up as high as possible. Fully extend your entire body, reaching overhead as far as possible. As you land, absorb your impact through the legs.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Rocket_Jump/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Rocket_Jump'),
  ('russian_twist', 'Russian Twist', 'Russian Twist',
   'Setz dich hin, die Knie gebeugt, und lehn den Oberkörper so weit zurück, dass Rumpf und Oberschenkel ein V bilden. Die Arme sind vor dem Körper gestreckt, die Hände gefaltet. Dreh den Oberkörper langsam zu einer Seite, kurz halten und zur anderen wechseln. Der Rücken bleibt gerade, die Drehung kommt aus dem Rumpf.',
   'Lie down on the floor placing your feet either under something that will not move or by having a partner hold them. Your legs should be bent at the knees. Elevate your upper body so that it creates an imaginary V-shape with your thighs. Your arms should be fully extended in front of you perpendicular to your torso and with the hands clasped. This is the starting position. Twist your torso to the right side until your arms are parallel with the floor while breathing out. Hold the contraction for a second and move back to the starting position while breathing out. Now move to the opposite side performing the same techniques you applied to the right side. Repeat for the recommended amount of repetitions.',
   'strength', 'intermediate', 'bodyweight',
   '/uebungen/Russian_Twist/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Russian_Twist'),
  ('scissors_jump', 'Scherensprung', 'Scissors Jump',
   'Wie der Sprung aus dem Ausfallschritt, nur wechselst du in der Luft die Beine: Das vordere geht nach hinten, das hintere nach vorn. Landen wieder im Ausfallschritt und sofort den nächsten Sprung anschließen. Die Landung weich über die Beine abfangen.',
   'Assume a lunge stance position with one foot forward with the knee bent, and the rear knee nearly touching the ground. Ensure that the front knee is over the midline of the foot. Extending through both legs, jump as high as possible, swinging your arms to gain lift. As you jump as high as you can, switch the position of your legs, moving your front leg to the back and the rear leg to the front. As you land, absorb the impact through the legs by adopting the lunge position, and repeat.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Scissors_Jump/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Scissors_Jump'),
  ('seated_glute', 'Gesäßdehnung im Sitzen', 'Seated Glute',
   'Setz dich hin, die Knie gebeugt, und leg einen Knöchel auf das gegenüberliegende Knie. Lehn dich mit geradem Rücken langsam nach vorn, bis du die Dehnung tief im Gesäß spürst. Zwanzig bis dreißig Sekunden halten und ruhig weiteratmen, dann die Seite wechseln.',
   'In a seated position with your knees bent, cross one ankle over the opposite knee. Your partner will stand behind you. Now, lean forward as your partner braces your shoulders with their hands. This will be your starting position. Attempt to push your torso back for 10-20 seconds, as your partner prevents any actual movement of your torso. Now relax your muscles as your partner increases the stretch by gently pushing your torso forward for 10-20 seconds.',
   'mobility', 'advanced', 'bodyweight',
   '/uebungen/Seated_Glute/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Seated_Glute'),
  ('side_bridge', 'Seitstütz', 'Side Bridge',
   'Leg dich auf die Seite und stütz dich auf den unteren Unterarm, der Ellbogen unter der Schulter. Heb die Hüfte an, bis Schulter, Hüfte und Füße eine Linie bilden. Halte die Position ruhig, ohne dass das Becken nach unten sackt oder nach hinten kippt. Dann die Seite wechseln.',
   '',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Side_Bridge/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Side_Bridge'),
  ('side_leg_raises', 'Beinschwingen zur Seite', 'Side Leg Raises',
   'Stell dich neben eine Stuhllehne und halte dich fest. Schwing ein gestrecktes Bein seitlich nach außen und im Rückschwung vor dem Standbein vorbei nach innen. Fünf bis zehn Mal je Seite, den Bewegungsumfang dabei langsam vergrößern. Gute Vorbereitung vor dem Lauf – nicht als Dehnung mit Halten gedacht.',
   'Stand next to a chair, which you may hold onto as a support. Stand on one leg. This will be your starting position. Keeping your leg straight, raise it as far out to the side as possible, and swing it back down, allowing it to cross the opposite leg. Repeat this swinging motion 5-10 times, increasing the range of motion as you do so.',
   'mobility', 'beginner', 'bodyweight',
   '/uebungen/Side_Leg_Raises/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Side_Leg_Raises'),
  ('single_leg_butt_kick', 'Einbeiniges Anfersen im Sprung', 'Single Leg Butt Kick',
   'Steh auf einem Bein, das andere Knie ist angehoben. Spring vom Standbein ab, indem du Hüfte, Knie und Sprunggelenk streckst. Zieh unmittelbar die Ferse des Absprungbeins zum Gesäß und setz zur Landung wieder auf. Das andere Bein bleibt die ganze Zeit in seiner Position.',
   'Begin by standing on one leg, with the bent knee raised. This will be your start position. Using a countermovement jump, take off upward by extending the hip, knee, and ankle of the grounded leg. Immediately flex the knee and attempt to touch your butt with the heel of your jumping leg. Return the leg to a partially bent position underneath the hips and land. Your opposite leg should stay in relatively the same position throughout the drill.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Single_Leg_Butt_Kick/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Single_Leg_Butt_Kick'),
  ('single_leg_glute_bridge', 'Einbeinige Hüftbrücke', 'Single Leg Glute Bridge',
   'Leg dich auf den Rücken, ein Fuß steht auf, das andere Knie ziehst du zur Brust. Drück über die Ferse des Standbeins die Hüfte nach oben, bis Oberschenkel und Rumpf eine Linie bilden. Kurz halten, langsam ablegen. Das Becken bleibt waagerecht und kippt nicht zur Seite.',
   'Lay on the floor with your feet flat and knees bent. Raise one leg off of the ground, pulling the knee to your chest. This will be your starting position. Execute the movement by driving through the heel, extending your hip upward and raising your glutes off of the ground. Extend as far as possible, pause and then return to the starting position.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Single_Leg_Glute_Bridge/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Single_Leg_Glute_Bridge'),
  ('spider_crawl', 'Spider Crawl', 'Spider Crawl',
   'Geh in die Liegestützposition, der Körper bildet eine gerade Linie. Zieh ein Knie seitlich nach außen bis Richtung Ellbogen und führ es zurück. Dann die andere Seite. Die Hüfte bleibt tief, das Becken dreht sich nicht weg – die Spannung im Rumpf hältst du durchgehend.',
   'Begin in a prone position on the floor. Support your weight on your hands and toes, with your feet together and your body straight. Your arms should be bent to 90 degrees. This will be your starting position. Initiate the movement by raising one foot off of the ground. Externally rotate the leg and bring the knee toward your elbow, as far forward as possible. Return this leg to the starting position and repeat on the opposite side.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Spider_Crawl/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Spider_Crawl'),
  ('split_jump', 'Sprung aus dem Ausfallschritt', 'Split Jump',
   'Geh in den Ausfallschritt, das vordere Knie über dem Fuß, das hintere fast am Boden. Streck beide Beine explosiv und spring so hoch wie möglich, die Arme geben Schwung. In der Luft führst du die Füße zusammen und setzt sie zur Landung wieder in die Ausgangsstellung. Die Landung weich abfedern.',
   'Assume a lunge stance position with one foot forward with the knee bent, and the rear knee nearly touching the ground. Ensure that the front knee is over the midline of the foot. Extending through both legs, jump as high as possible, swinging your arms to gain lift. As you jump, bring your feet together, and move them back to their initial positions as you land. Absorb the impact by reverting back to the starting position.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Split_Jump/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Split_Jump'),
  ('split_squat_with_dumbbells', 'Bulgarische Kniebeuge mit Kurzhanteln', 'Split Squat with Dumbbells',
   'Stell den hinteren Fuß erhöht ab, etwa auf eine Bank, und geh mit dem vorderen Bein in Schrittstellung. Je eine Kurzhantel hängt neben dem Körper. Senke den Körper ab, bis das vordere Bein etwa im rechten Winkel steht, und drück dich über die Ferse wieder hoch. Das vordere Knie bleibt über dem Fuß.',
   'Position yourself into a staggered stance with the rear foot elevated and front foot forward. Hold a dumbbell in each hand, letting them hang at the sides. This will be your starting position. Begin by descending, flexing your knee and hip to lower your body down. Maintain good posture througout the movement. Keep the front knee in line with the foot as you perform the exercise. At the bottom of the movement, drive through the heel to extend the knee and hip to return to the starting position.',
   'strength', 'beginner', 'gym',
   '/uebungen/Split_Squat_with_Dumbbells/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Split_Squat_with_Dumbbells'),
  ('standing_dumbbell_calf_raise', 'Wadenheben im Stand mit Kurzhanteln', 'Standing Dumbbell Calf Raise',
   'Stell die Fußballen auf eine stabile Erhöhung von zwei bis drei Zentimetern, die Fersen hängen frei. In jeder Hand eine Kurzhantel. Drück dich langsam auf die Zehenspitzen, oben eine Sekunde halten, dann die Fersen kontrolliert unter das Niveau absenken. Für Laufende besonders wichtig – die Wade trägt bei jedem Schritt ein Vielfaches des Körpergewichts.',
   'Stand with your torso upright holding two dumbbells in your hands by your sides. Place the ball of the foot on a sturdy and stable wooden board (that is around 2-3 inches tall) while your heels extend off and touch the floor. This will be your starting position. With the toes pointing either straight (to hit all parts equally), inwards (for emphasis on the outer head) or outwards (for emphasis on the inner head), raise the heels off the floor as you exhale by contracting the calves. Hold the top contraction for a second. As you inhale, go back to the starting position by slowly lowering the heels. Repeat for the recommended amount of times.',
   'strength', 'intermediate', 'gym',
   '/uebungen/Standing_Dumbbell_Calf_Raise/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Standing_Dumbbell_Calf_Raise'),
  ('standing_hip_circles', 'Hüftkreisen im Stand', 'Standing Hip Circles',
   'Stell dich auf ein Bein und halte dich an etwas Festem fest. Heb das freie Knie auf Hüfthöhe an. Führ das Knie in einem möglichst großen Kreis nach außen, nach hinten und wieder nach vorn. Langsam ausführen, mehrere Wiederholungen, dann die Seite wechseln.',
   'Begin standing on one leg, holding to a vertical support. Raise the unsupported knee to 90 degrees. This will be your starting position. Open the hip as far as possible, attempting to make a big circle with your knee. Perform this movement slowly for a number of repetitions, and repeat on the other side.',
   'mobility', 'beginner', 'bodyweight',
   '/uebungen/Standing_Hip_Circles/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Standing_Hip_Circles'),
  ('standing_long_jump', 'Standweitsprung', 'Standing Long Jump',
   'Stell dich schulterbreit in eine leichte Kniebeuge. Hol mit beiden Armen Schwung und spring so weit wie möglich nach vorn. Versuch, mit den Füßen weit vorn zu landen, und fang die Landung weich über die Beine ab. Am besten auf weichem Untergrund. Die Weite lässt sich messen und ist ein guter Fortschrittsmesser.',
   'This drill is best done in sand or other soft landing surface. Ensure that you are able to measure distance. Stand in a partial squat stance with feet shoulder width apart. Utilizing a big arm swing and a countermovement of the legs, jump forward as far as you can. Attempt to land with your feet out in front you, reaching as far as possible with your legs. Measure the distance from your landing point to the starting point and track results.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Standing_Long_Jump/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Standing_Long_Jump'),
  ('star_jump', 'Sternsprung', 'Star Jump',
   'Stell dich locker schulterbreit hin, die Arme am Körper. Geh halb in die Knie und spring explosiv hoch, dabei spreizt du Arme und Beine wie ein Stern vom Körper weg. Vor der Landung Arme und Beine wieder zusammenführen und weich abfedern.',
   'Begin in a relaxed stance with your feet shoulder width apart and hold your arms close to the body. To initiate the move, squat down halfway and explode back up as high as possible. Fully extend your entire body, spreading your legs and arms away from the body. As you land, bring your limbs back in and absorb your impact through the legs.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Star_Jump/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Star_Jump'),
  ('step_up_with_knee_raise', 'Aufsteigen mit Knieheben', 'Step-up with Knee Raise',
   'Stell dich vor eine Stufe oder Bank in passender Höhe. Steig mit einem Bein hinauf und streck Hüfte und Knie vollständig. Zieh dabei das andere Knie so hoch wie möglich nach oben. Kontrolliert wieder absteigen, dann die Seite wechseln. Sehr laufnah, weil du Standbein und Schwungbein gleichzeitig trainierst.',
   'Stand facing a box or bench of an appropriate height with your feet together. This will be your starting position. Begin the movement by stepping up, putting your left foot on the top of the bench. Extend through the hip and knee of your front leg to stand up on the box. As you stand on the box with your left leg, flex your right knee and hip, bringing your knee as high as you can. Reverse this motion to step down off the box, and then repeat the sequence on the opposite leg.',
   'strength', 'beginner', 'bodyweight',
   '/uebungen/Step-up_with_Knee_Raise/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Step-up_with_Knee_Raise'),
  ('stiff_legged_dumbbell_deadlift', 'Kreuzheben mit gestreckten Beinen', 'Stiff-Legged Dumbbell Deadlift',
   'Steh aufrecht mit je einer Kurzhantel, die Knie ganz leicht gebeugt und während der Übung unverändert. Kipp aus der Hüfte nach vorn und führ die Hanteln dicht am Bein nach unten, bis du die hintere Oberschenkelmuskulatur ziehen spürst. Der Rücken bleibt dabei durchgehend gerade. Richte dich über die Hüfte wieder auf.',
   'Grasp a couple of dumbbells holding them by your side at arm''s length. Stand with your torso straight and your legs spaced using a shoulder width or narrower stance. The knees should be slightly bent. This is your starting position. Keeping the knees stationary, lower the dumbbells to over the top of your feet by bending at the waist while keeping your back straight. Keep moving forward as if you were going to pick something from the floor until you feel a stretch on the hamstrings. Exhale as you perform this movement Start bringing your torso up straight again by extending your hips and waist until you are back at the starting position. Inhale as you perform this movement. Repeat for the recommended amount of repetitions.',
   'strength', 'beginner', 'gym',
   '/uebungen/Stiff-Legged_Dumbbell_Deadlift/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Stiff-Legged_Dumbbell_Deadlift'),
  ('superman', 'Superman', 'Superman',
   'Leg dich flach auf den Bauch, die Arme nach vorn gestreckt. Heb Arme, Brust und Beine gleichzeitig vom Boden ab und halte zwei Sekunden, während du ausatmest. Der Blick bleibt zum Boden gerichtet, der Nacken lang. Langsam wieder ablegen.',
   'To begin, lie straight and face down on the floor or exercise mat. Your arms should be fully extended in front of you. This is the starting position. Simultaneously raise your arms, legs, and chest off of the floor and hold this contraction for 2 seconds. Tip: Squeeze your lower back to get the best results from this exercise. Remember to exhale during this movement. Note: When holding the contracted position, you should look like superman when he is flying. Slowly begin to lower your arms, legs and chest back down to the starting position while inhaling. Repeat for the recommended amount of repetitions prescribed in your program.',
   'mobility', 'beginner', 'bodyweight',
   '/uebungen/Superman/0.jpg', 'free-exercise-db', 'https://github.com/yuhonas/free-exercise-db', 'Unlicense (gemeinfrei)', 'Superman')
on conflict (slug) do nothing;


-- Muskelgruppen je Uebung -------------------------------------
-- Die Unterabfragen loesen die Kennungen ueber die Slugs auf, damit die
-- Migration keine fest verdrahteten UUIDs enthaelt.

insert into public.exercise_muscles (exercise_id, muscle_group_id, role) values
  ((select id from public.exercises where slug = '90_90_hamstring'), (select id from public.muscle_groups where slug = 'hamstrings'), 'primary'),
  ((select id from public.exercises where slug = '90_90_hamstring'), (select id from public.muscle_groups where slug = 'calves'), 'secondary'),
  ((select id from public.exercises where slug = 'adductor'), (select id from public.muscle_groups where slug = 'adductors'), 'primary'),
  ((select id from public.exercises where slug = 'all_fours_quad_stretch'), (select id from public.muscle_groups where slug = 'quads'), 'primary'),
  ((select id from public.exercises where slug = 'ball_leg_curl'), (select id from public.muscle_groups where slug = 'hamstrings'), 'primary'),
  ((select id from public.exercises where slug = 'ball_leg_curl'), (select id from public.muscle_groups where slug = 'calves'), 'secondary'),
  ((select id from public.exercises where slug = 'ball_leg_curl'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'band_hip_adductions'), (select id from public.muscle_groups where slug = 'adductors'), 'primary'),
  ((select id from public.exercises where slug = 'bench_jump'), (select id from public.muscle_groups where slug = 'quads'), 'primary'),
  ((select id from public.exercises where slug = 'bench_jump'), (select id from public.muscle_groups where slug = 'calves'), 'secondary'),
  ((select id from public.exercises where slug = 'bench_jump'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'bench_jump'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'bent_knee_hip_raise'), (select id from public.muscle_groups where slug = 'abs'), 'primary'),
  ((select id from public.exercises where slug = 'bodyweight_squat'), (select id from public.muscle_groups where slug = 'quads'), 'primary'),
  ((select id from public.exercises where slug = 'bodyweight_squat'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'bodyweight_squat'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'butt_lift_bridge'), (select id from public.muscle_groups where slug = 'glutes'), 'primary'),
  ((select id from public.exercises where slug = 'butt_lift_bridge'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'calf_raises_with_bands'), (select id from public.muscle_groups where slug = 'calves'), 'primary'),
  ((select id from public.exercises where slug = 'calves_smr'), (select id from public.muscle_groups where slug = 'calves'), 'primary'),
  ((select id from public.exercises where slug = 'cross_body_crunch'), (select id from public.muscle_groups where slug = 'abs'), 'primary'),
  ((select id from public.exercises where slug = 'dead_bug'), (select id from public.muscle_groups where slug = 'abs'), 'primary'),
  ((select id from public.exercises where slug = 'double_leg_butt_kick'), (select id from public.muscle_groups where slug = 'quads'), 'primary'),
  ((select id from public.exercises where slug = 'double_leg_butt_kick'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'double_leg_butt_kick'), (select id from public.muscle_groups where slug = 'adductors'), 'secondary'),
  ((select id from public.exercises where slug = 'double_leg_butt_kick'), (select id from public.muscle_groups where slug = 'calves'), 'secondary'),
  ((select id from public.exercises where slug = 'double_leg_butt_kick'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'dumbbell_lunges'), (select id from public.muscle_groups where slug = 'quads'), 'primary'),
  ((select id from public.exercises where slug = 'dumbbell_lunges'), (select id from public.muscle_groups where slug = 'calves'), 'secondary'),
  ((select id from public.exercises where slug = 'dumbbell_lunges'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'dumbbell_lunges'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'dumbbell_rear_lunge'), (select id from public.muscle_groups where slug = 'quads'), 'primary'),
  ((select id from public.exercises where slug = 'dumbbell_rear_lunge'), (select id from public.muscle_groups where slug = 'calves'), 'secondary'),
  ((select id from public.exercises where slug = 'dumbbell_rear_lunge'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'dumbbell_rear_lunge'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'dumbbell_seated_one_leg_calf_raise'), (select id from public.muscle_groups where slug = 'calves'), 'primary'),
  ((select id from public.exercises where slug = 'fast_skipping'), (select id from public.muscle_groups where slug = 'quads'), 'primary'),
  ((select id from public.exercises where slug = 'fast_skipping'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'fast_skipping'), (select id from public.muscle_groups where slug = 'adductors'), 'secondary'),
  ((select id from public.exercises where slug = 'fast_skipping'), (select id from public.muscle_groups where slug = 'calves'), 'secondary'),
  ((select id from public.exercises where slug = 'fast_skipping'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'flutter_kicks'), (select id from public.muscle_groups where slug = 'glutes'), 'primary'),
  ((select id from public.exercises where slug = 'flutter_kicks'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'glute_kickback'), (select id from public.muscle_groups where slug = 'glutes'), 'primary'),
  ((select id from public.exercises where slug = 'glute_kickback'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'groiners'), (select id from public.muscle_groups where slug = 'adductors'), 'primary'),
  ((select id from public.exercises where slug = 'hamstring_smr'), (select id from public.muscle_groups where slug = 'hamstrings'), 'primary'),
  ((select id from public.exercises where slug = 'hip_extension_with_bands'), (select id from public.muscle_groups where slug = 'glutes'), 'primary'),
  ((select id from public.exercises where slug = 'hip_extension_with_bands'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'hip_flexion_with_band'), (select id from public.muscle_groups where slug = 'quads'), 'primary'),
  ((select id from public.exercises where slug = 'hyperextensions_with_no_hyperextension_bench'), (select id from public.muscle_groups where slug = 'lower_back'), 'primary'),
  ((select id from public.exercises where slug = 'hyperextensions_with_no_hyperextension_bench'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'hyperextensions_with_no_hyperextension_bench'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'iliotibial_tract_smr'), (select id from public.muscle_groups where slug = 'glutes'), 'primary'),
  ((select id from public.exercises where slug = 'inchworm'), (select id from public.muscle_groups where slug = 'hamstrings'), 'primary'),
  ((select id from public.exercises where slug = 'knee_circles'), (select id from public.muscle_groups where slug = 'calves'), 'primary'),
  ((select id from public.exercises where slug = 'knee_circles'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'knee_circles'), (select id from public.muscle_groups where slug = 'quads'), 'secondary'),
  ((select id from public.exercises where slug = 'knee_tuck_jump'), (select id from public.muscle_groups where slug = 'hamstrings'), 'primary'),
  ((select id from public.exercises where slug = 'knee_tuck_jump'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'knee_tuck_jump'), (select id from public.muscle_groups where slug = 'adductors'), 'secondary'),
  ((select id from public.exercises where slug = 'knee_tuck_jump'), (select id from public.muscle_groups where slug = 'calves'), 'secondary'),
  ((select id from public.exercises where slug = 'knee_tuck_jump'), (select id from public.muscle_groups where slug = 'quads'), 'secondary'),
  ((select id from public.exercises where slug = 'lateral_bound'), (select id from public.muscle_groups where slug = 'adductors'), 'primary'),
  ((select id from public.exercises where slug = 'lateral_bound'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'lateral_bound'), (select id from public.muscle_groups where slug = 'calves'), 'secondary'),
  ((select id from public.exercises where slug = 'lateral_bound'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'lateral_bound'), (select id from public.muscle_groups where slug = 'quads'), 'secondary'),
  ((select id from public.exercises where slug = 'lower_back_smr'), (select id from public.muscle_groups where slug = 'lower_back'), 'primary'),
  ((select id from public.exercises where slug = 'lying_crossover'), (select id from public.muscle_groups where slug = 'glutes'), 'primary'),
  ((select id from public.exercises where slug = 'lying_glute'), (select id from public.muscle_groups where slug = 'glutes'), 'primary'),
  ((select id from public.exercises where slug = 'lying_prone_quadriceps'), (select id from public.muscle_groups where slug = 'quads'), 'primary'),
  ((select id from public.exercises where slug = 'monster_walk'), (select id from public.muscle_groups where slug = 'glutes'), 'primary'),
  ((select id from public.exercises where slug = 'natural_glute_ham_raise'), (select id from public.muscle_groups where slug = 'hamstrings'), 'primary'),
  ((select id from public.exercises where slug = 'natural_glute_ham_raise'), (select id from public.muscle_groups where slug = 'calves'), 'secondary'),
  ((select id from public.exercises where slug = 'natural_glute_ham_raise'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'natural_glute_ham_raise'), (select id from public.muscle_groups where slug = 'lower_back'), 'secondary'),
  ((select id from public.exercises where slug = 'peroneals_smr'), (select id from public.muscle_groups where slug = 'calves'), 'primary'),
  ((select id from public.exercises where slug = 'piriformis_smr'), (select id from public.muscle_groups where slug = 'glutes'), 'primary'),
  ((select id from public.exercises where slug = 'plank'), (select id from public.muscle_groups where slug = 'abs'), 'primary'),
  ((select id from public.exercises where slug = 'quadriceps_smr'), (select id from public.muscle_groups where slug = 'quads'), 'primary'),
  ((select id from public.exercises where slug = 'reverse_crunch'), (select id from public.muscle_groups where slug = 'abs'), 'primary'),
  ((select id from public.exercises where slug = 'rocket_jump'), (select id from public.muscle_groups where slug = 'quads'), 'primary'),
  ((select id from public.exercises where slug = 'rocket_jump'), (select id from public.muscle_groups where slug = 'calves'), 'secondary'),
  ((select id from public.exercises where slug = 'rocket_jump'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'russian_twist'), (select id from public.muscle_groups where slug = 'abs'), 'primary'),
  ((select id from public.exercises where slug = 'russian_twist'), (select id from public.muscle_groups where slug = 'lower_back'), 'secondary'),
  ((select id from public.exercises where slug = 'scissors_jump'), (select id from public.muscle_groups where slug = 'quads'), 'primary'),
  ((select id from public.exercises where slug = 'scissors_jump'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'scissors_jump'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'seated_glute'), (select id from public.muscle_groups where slug = 'glutes'), 'primary'),
  ((select id from public.exercises where slug = 'seated_glute'), (select id from public.muscle_groups where slug = 'adductors'), 'secondary'),
  ((select id from public.exercises where slug = 'side_bridge'), (select id from public.muscle_groups where slug = 'abs'), 'primary'),
  ((select id from public.exercises where slug = 'side_bridge'), (select id from public.muscle_groups where slug = 'shoulders'), 'secondary'),
  ((select id from public.exercises where slug = 'side_leg_raises'), (select id from public.muscle_groups where slug = 'adductors'), 'primary'),
  ((select id from public.exercises where slug = 'single_leg_butt_kick'), (select id from public.muscle_groups where slug = 'quads'), 'primary'),
  ((select id from public.exercises where slug = 'single_leg_butt_kick'), (select id from public.muscle_groups where slug = 'calves'), 'secondary'),
  ((select id from public.exercises where slug = 'single_leg_butt_kick'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'single_leg_glute_bridge'), (select id from public.muscle_groups where slug = 'glutes'), 'primary'),
  ((select id from public.exercises where slug = 'single_leg_glute_bridge'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'spider_crawl'), (select id from public.muscle_groups where slug = 'abs'), 'primary'),
  ((select id from public.exercises where slug = 'spider_crawl'), (select id from public.muscle_groups where slug = 'chest'), 'secondary'),
  ((select id from public.exercises where slug = 'spider_crawl'), (select id from public.muscle_groups where slug = 'shoulders'), 'secondary'),
  ((select id from public.exercises where slug = 'spider_crawl'), (select id from public.muscle_groups where slug = 'triceps'), 'secondary'),
  ((select id from public.exercises where slug = 'split_jump'), (select id from public.muscle_groups where slug = 'quads'), 'primary'),
  ((select id from public.exercises where slug = 'split_jump'), (select id from public.muscle_groups where slug = 'calves'), 'secondary'),
  ((select id from public.exercises where slug = 'split_jump'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'split_jump'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'split_squat_with_dumbbells'), (select id from public.muscle_groups where slug = 'quads'), 'primary'),
  ((select id from public.exercises where slug = 'split_squat_with_dumbbells'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'split_squat_with_dumbbells'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'standing_dumbbell_calf_raise'), (select id from public.muscle_groups where slug = 'calves'), 'primary'),
  ((select id from public.exercises where slug = 'standing_hip_circles'), (select id from public.muscle_groups where slug = 'glutes'), 'primary'),
  ((select id from public.exercises where slug = 'standing_hip_circles'), (select id from public.muscle_groups where slug = 'adductors'), 'secondary'),
  ((select id from public.exercises where slug = 'standing_long_jump'), (select id from public.muscle_groups where slug = 'quads'), 'primary'),
  ((select id from public.exercises where slug = 'standing_long_jump'), (select id from public.muscle_groups where slug = 'calves'), 'secondary'),
  ((select id from public.exercises where slug = 'standing_long_jump'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'standing_long_jump'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'star_jump'), (select id from public.muscle_groups where slug = 'quads'), 'primary'),
  ((select id from public.exercises where slug = 'star_jump'), (select id from public.muscle_groups where slug = 'calves'), 'secondary'),
  ((select id from public.exercises where slug = 'star_jump'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'star_jump'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'star_jump'), (select id from public.muscle_groups where slug = 'shoulders'), 'secondary'),
  ((select id from public.exercises where slug = 'step_up_with_knee_raise'), (select id from public.muscle_groups where slug = 'glutes'), 'primary'),
  ((select id from public.exercises where slug = 'step_up_with_knee_raise'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary'),
  ((select id from public.exercises where slug = 'step_up_with_knee_raise'), (select id from public.muscle_groups where slug = 'quads'), 'secondary'),
  ((select id from public.exercises where slug = 'stiff_legged_dumbbell_deadlift'), (select id from public.muscle_groups where slug = 'hamstrings'), 'primary'),
  ((select id from public.exercises where slug = 'stiff_legged_dumbbell_deadlift'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'stiff_legged_dumbbell_deadlift'), (select id from public.muscle_groups where slug = 'lower_back'), 'secondary'),
  ((select id from public.exercises where slug = 'superman'), (select id from public.muscle_groups where slug = 'lower_back'), 'primary'),
  ((select id from public.exercises where slug = 'superman'), (select id from public.muscle_groups where slug = 'glutes'), 'secondary'),
  ((select id from public.exercises where slug = 'superman'), (select id from public.muscle_groups where slug = 'hamstrings'), 'secondary')
on conflict do nothing;
